### ISSUE TITLE
open doc

### ISSUE THREAD

**Issue by VB10** [gulayfirat/todo_app_with_hive_cubit#3]
https://github.com/gulayfirat/todo_app_with_hive_cubit/blob/803d19350de3a4d5b6f95c1e158ee73bee555bd3/lib/core/base/base_model.dart#L3

bu tarz generic katmanlarini hepsininde muhakkak bir dokuman eklemek lazim ustune bastice neden misal create instance gibi

**Comment by gulayfirat** [comment]
Document added
