### ISSUE TITLE
methodlar private

### ISSUE THREAD

**Issue by VB10** [gulayfirat/todo_app_with_hive_cubit#5]
https://github.com/gulayfirat/todo_app_with_hive_cubit/blob/803d19350de3a4d5b6f95c1e158ee73bee555bd3/lib/feature/note/addNote/viewModel/add_note_cubit.dart#L26

sadece bu classta kullanilan methodlari private yapmayi unutmayalim
methodlar dynamic almasin

**Comment by gulayfirat** [comment]
Completed private metod
