### ISSUE TITLE
very good anlayisis

### ISSUE THREAD

**Issue by VB10** [gulayfirat/todo_app_with_hive_cubit#6]
https://github.com/gulayfirat/todo_app_with_hive_cubit/blob/803d19350de3a4d5b6f95c1e158ee73bee555bd3/pubspec.yaml#L61
flutter lints biraz dusuk kaliyor ondan very good analyiss gecip tekrar projeyi duzeltelim 

readme update sart

**Comment by gulayfirat** [comment]
very good analyiss added
